name: TCC-web-app GitHub Actions v1
on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          cd lang/kotlin
          gradle test
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Run reports script
        run: node report/gradleReport.js
      - name: Auto commit readme
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change (readme)!
          branch: add-readme-reports
          file_pattern: 'README.md'